INSERT INTO tipos_gastos_personales VALUES (1, 'ARRIENDO', 1);
INSERT INTO tipos_gastos_personales VALUES (32, 'OPERACIÓN TURISTICA', 6);
INSERT INTO tipos_gastos_personales VALUES (2, 'INTERÉSES PRESTAMO 
HIPOTECARIO', 1);
INSERT INTO tipos_gastos_personales VALUES (3, 'SERVICIOS BÁSICOS ', 1);
INSERT INTO tipos_gastos_personales VALUES (4, 'IMPUESTO PREDIAL', 1);
INSERT INTO tipos_gastos_personales VALUES (5, 'PENSIONES ALIMENTICIAS', 1);
INSERT INTO tipos_gastos_personales VALUES (33, 'INTERMECIACIÓN TURÍSTICA', 6);
INSERT INTO tipos_gastos_personales VALUES (6, 'OTROS GASTOS', 1);
INSERT INTO tipos_gastos_personales VALUES (7, 'MATRÌCULA Y PENSIÓN', 2);
INSERT INTO tipos_gastos_personales VALUES (8, 'ÚTILES Y TEXTOS ESCOLARES', 2);
INSERT INTO tipos_gastos_personales VALUES (34, 'PARQUES DE ATRACCIONES', 6);
INSERT INTO tipos_gastos_personales VALUES (9, 'ECUACIÓN PARA PERSONAS CON DISCAPACIDAD', 2);
INSERT INTO tipos_gastos_personales VALUES (10, 'CUIDADO Y/O DESARROLLO INFANTIL', 2);
INSERT INTO tipos_gastos_personales VALUES (11, 'UNIFORMES', 2);
INSERT INTO tipos_gastos_personales VALUES (35, 'PENSIONES ALIMENTICIAS', 6);
INSERT INTO tipos_gastos_personales VALUES (12, 'ARTES VIVAS Y ESCÉNICAS', 2);
INSERT INTO tipos_gastos_personales VALUES (13, 'ARTES PLÁSTICAS, VISUALES Y APLICADAS', 2);
INSERT INTO tipos_gastos_personales VALUES (14, 'ARTES LITERARIAS Y NARRATIVAS', 2);
INSERT INTO tipos_gastos_personales VALUES (15, 'ARTES CINEMATOGRÁFICAS Y AUDIOVISUALES', 2);
INSERT INTO tipos_gastos_personales VALUES (16, 'PROMOCIÓN Y DIFUCIÓN DE LA MEMORIA SOCIAL Y EL PATRIMONIO', 2);
INSERT INTO tipos_gastos_personales VALUES (17, 'ARTESANÍAS', 2);
INSERT INTO tipos_gastos_personales VALUES (18, 'PENSIONES ALIMENTICIAS', 2);
INSERT INTO tipos_gastos_personales VALUES (19, 'HONORARIOS PROFESIONALES DE SALUD', 3);
INSERT INTO tipos_gastos_personales VALUES (20, 'SERVICIOS DE SALUD', 3);
INSERT INTO tipos_gastos_personales VALUES (21, 'MEDICINAS Y OTROS', 3);
INSERT INTO tipos_gastos_personales VALUES (22, 'DEDUCIBLE DEL SEGURO', 3);
INSERT INTO tipos_gastos_personales VALUES (23, 'PENSIONES ALIMENTICIAS', 3);
INSERT INTO tipos_gastos_personales VALUES (24, 'OTROS GASTOS', 3);
INSERT INTO tipos_gastos_personales VALUES (25, 'ALIMENTOS', 4);
INSERT INTO tipos_gastos_personales VALUES (26, 'PENSIONES ALIMENTICIAS', 4);
INSERT INTO tipos_gastos_personales VALUES (27, 'PRENDAS DE VESTIR', 5);
INSERT INTO tipos_gastos_personales VALUES (28, 'PENSIONES ALIMENTICIAS', 5);
INSERT INTO tipos_gastos_personales VALUES (29, 'ALOJAMIENTO', 6);
INSERT INTO tipos_gastos_personales VALUES (30, 'TRANSPORTE', 6);
INSERT INTO tipos_gastos_personales VALUES (31, 'SERVICIO DE ALIMENTOS Y BEBIDAS', 6);
INSERT INTO tipos_gastos_personales VALUES (1000, 'OTROS GASTOS', 1000);