  calcularpreciofinal[m
  cambiosfacturaventa2[m
  centralizarautorizacion[m
  colegio_actual[m
  dunkel_actual[m
  expirar_esquema[m
  f_dannys_actual[m
  farmacia_olivos_actual[m
  farmacia_olivos_actual_cahuas[m
  lacasadel_perno_actual[m
  lacasadelfreno_actual[m
  main[m
  micomisariato_actual[m
  mivajilla[m
  nuevosparametros[m
  plasticonos[m
  plastytodo_actual[m
  promollantas_actual[m
  reportecxc[m
  subircompras[m
* [32munidades_medida_producampo[m
  venta_unidad_meidida[m
